# Generated by Django 4.0.3 on 2022-03-13 14:17

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık')),
                ('url_name', models.SlugField(blank=True, help_text='This will be filled automatically', max_length=500, verbose_name='Sayfa Uzantısı')),
                ('slider_image', image_optimizer.fields.OptimizedImageField(blank=True, help_text='1920x850', null=True, upload_to='newadmin/flatpages/images', verbose_name="Slider Resmi'")),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Kullan')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
            },
        ),
    ]
