# Generated by Django 4.0.3 on 2022-03-13 14:23

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='detail_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='1200x662', null=True, upload_to='newadmin/flatpages/images', verbose_name="Detay Sayfa Resmi'"),
        ),
    ]
