# Generated by Django 4.0.3 on 2022-03-16 16:25

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_expl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='1200x662', null=True, upload_to='media/', verbose_name="Detay Sayfa Resmi'"),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slider_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='1920x850', null=True, upload_to='media/', verbose_name="Slider Resmi'"),
        ),
    ]
