# Generated by Django 4.0.3 on 2022-03-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_expl',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
    ]
