# Generated by Django 4.0.3 on 2022-03-28 12:34

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_info_alter_navigation_options_blog_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['order'], 'verbose_name': 'Info Yazısı', 'verbose_name_plural': 'Info Yazıları'},
        ),
        migrations.AlterField(
            model_name='info',
            name='homepage_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='550x465', null=True, upload_to='info/', verbose_name="Anasayfa Resmi'"),
        ),
    ]
