# Generated by Django 4.0.3 on 2022-04-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_info_options_alter_info_homepage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['create_date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
    ]
