# Generated by Django 4.0.3 on 2022-04-10 13:03

import app.models
import ckeditor.fields
from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık')),
                ('short_expl', models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama')),
                ('expl', ckeditor.fields.RichTextField(null=True)),
                ('url_name', models.SlugField(blank=True, help_text='This will be filled automatically', max_length=500, verbose_name='Sayfa Uzantısı')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Kullan')),
                ('slider_image', image_optimizer.fields.OptimizedImageField(blank=True, help_text='1920x850', null=True, upload_to='blogs/', verbose_name="Slider Resmi'")),
                ('detail_image', image_optimizer.fields.OptimizedImageField(blank=True, help_text='1200x662', null=True, upload_to='blogs/', verbose_name="Detay Sayfa Resmi'")),
                ('homepage_image', image_optimizer.fields.OptimizedImageField(blank=True, help_text='1200x662', null=True, upload_to='blogs/', verbose_name="Detay Sayfa Resmi'")),
                ('visa_text', models.BooleanField(blank=True, default=False, null=True, verbose_name='Visa yazısı mı?')),
                ('blog_text', models.BooleanField(blank=True, default=False, null=True, verbose_name='Blog yazısı mı?')),
                ('create_date', models.DateField(default=app.models.return_date_time, verbose_name='Tarih')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['create_date'],
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
