# Generated by Django 4.0.3 on 2022-04-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_content_delete_blog_delete_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['create_date'], 'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
    ]
