# Generated by Django 4.0.3 on 2022-04-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(to='app.category', verbose_name='Alakalı Kategoriler'),
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.ManyToManyField(to='app.country', verbose_name='Alakalı Ülkeler'),
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(to='app.tag', verbose_name='Alakalı Etiketler'),
        ),
    ]
