# Generated by Django 4.0.3 on 2022-04-14 08:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_content_category_content_country_content_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ManyToManyField(blank=True, to='app.category', verbose_name='Alakalı Kategoriler'),
        ),
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.ManyToManyField(blank=True, to='app.country', verbose_name='Alakalı Ülkeler'),
        ),
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateField(blank=True, default=app.models.return_date_time, verbose_name='Tarih'),
        ),
    ]
