# Generated by Django 4.0.3 on 2022-04-14 08:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_content_category_alter_content_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateField(default=app.models.return_date_time, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.tag', verbose_name='Alakalı Etiketler'),
        ),
    ]
