# Generated by Django 4.0.3 on 2022-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_content_create_date_alter_content_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Kullan'),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Kullan'),
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Kullan'),
        ),
    ]
