# Generated by Django 4.0.3 on 2022-04-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_country_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.SlugField(blank=True, help_text='This will be filled automatically', max_length=500, verbose_name='Sayfa Uzantısı'),
        ),
        migrations.AddField(
            model_name='country',
            name='url_name',
            field=models.SlugField(blank=True, help_text='This will be filled automatically', max_length=500, verbose_name='Sayfa Uzantısı'),
        ),
        migrations.AddField(
            model_name='tag',
            name='url_name',
            field=models.SlugField(blank=True, help_text='This will be filled automatically', max_length=500, verbose_name='Sayfa Uzantısı'),
        ),
    ]
