# Generated by Django 4.0.3 on 2022-04-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_category_url_name_country_url_name_tag_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='blog_text',
        ),
        migrations.RemoveField(
            model_name='content',
            name='visa_text',
        ),
    ]
