# Generated by Django 4.0.3 on 2022-04-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_content_blog_text_remove_content_visa_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ülke Adı')),
            ],
            options={
                'verbose_name': 'Kıta',
                'verbose_name_plural': 'Kıtalar',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.continent'),
        ),
    ]
