# Generated by Django 4.0.3 on 2022-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_continent_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kıta Adı'),
        ),
    ]
