# Generated by Django 4.0.3 on 2022-07-12 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_category_expl'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='expl',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
