# Generated by Django 4.0.3 on 2022-07-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='QuickInfo',
        ),
        migrations.AlterModelOptions(
            name='quickinfo',
            options={'verbose_name': 'Quick Info', 'verbose_name_plural': 'Quick Info'},
        ),
    ]
