# Generated by Django 4.0.3 on 2022-07-16 10:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='country',
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='Alakalı Ülke'),
        ),
        migrations.AlterField(
            model_name='content',
            name='expl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
