# Generated by Django 4.0.3 on 2022-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_content_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Popüler Kategori mi?'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Popüler Etiket mi?'),
        ),
    ]
