# Generated by Django 4.0.3 on 2022-07-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_category_popular_alter_tag_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Google SEO Description'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords'),
        ),
    ]
