# Generated by Django 4.0.3 on 2022-07-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_content_description_content_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description'),
        ),
    ]
