# Generated by Django 4.0.3 on 2022-07-25 07:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_category_description_category_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='descriptionEs',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması Es', null=True, verbose_name='Google SEO Description Es'),
        ),
        migrations.AddField(
            model_name='content',
            name='descriptionFr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması Fr', null=True, verbose_name='Google SEO Description Fr'),
        ),
        migrations.AddField(
            model_name='content',
            name='descriptionHi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması Hi', null=True, verbose_name='Google SEO Description Hi'),
        ),
        migrations.AddField(
            model_name='content',
            name='descriptionTr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması Tr', null=True, verbose_name='Google SEO Description Tr'),
        ),
        migrations.AddField(
            model_name='content',
            name='descriptionVi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması Vi', null=True, verbose_name='Google SEO Description Vi'),
        ),
        migrations.AddField(
            model_name='content',
            name='explEs',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='explFr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='explHi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='explTr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='explVi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='headerEs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Es'),
        ),
        migrations.AddField(
            model_name='content',
            name='headerFr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Fr'),
        ),
        migrations.AddField(
            model_name='content',
            name='headerHi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Hi'),
        ),
        migrations.AddField(
            model_name='content',
            name='headerTr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Tr'),
        ),
        migrations.AddField(
            model_name='content',
            name='headerVi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Vi'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywordsEs',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın Es', null=True, verbose_name='Keywords Es'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywordsFr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın Fr', null=True, verbose_name='Keywords Fr'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywordsHi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın Hi', null=True, verbose_name='Keywords Hi'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywordsTr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın Tr', null=True, verbose_name='Keywords Tr'),
        ),
        migrations.AddField(
            model_name='content',
            name='keywordsVi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın Vi', null=True, verbose_name='Keywords Vi'),
        ),
        migrations.AddField(
            model_name='content',
            name='short_explEs',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Es'),
        ),
        migrations.AddField(
            model_name='content',
            name='short_explFr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Fr'),
        ),
        migrations.AddField(
            model_name='content',
            name='short_explHi',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Hi'),
        ),
        migrations.AddField(
            model_name='content',
            name='short_explTr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Tr'),
        ),
        migrations.AddField(
            model_name='content',
            name='short_explVi',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Vi'),
        ),
    ]
