# Generated by Django 4.0.3 on 2022-07-25 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_content_descriptiones_content_descriptionfr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='explEs',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Keywords Es'),
        ),
        migrations.AlterField(
            model_name='content',
            name='explFr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Keywords Fr'),
        ),
        migrations.AlterField(
            model_name='content',
            name='explHi',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Keywords Hi'),
        ),
        migrations.AlterField(
            model_name='content',
            name='explTr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Keywords Tr'),
        ),
        migrations.AlterField(
            model_name='content',
            name='explVi',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Keywords Vi'),
        ),
    ]
