# Generated by Django 4.0.3 on 2022-07-25 07:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_content_exples_alter_content_explfr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='descriptionEs',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Es'),
        ),
        migrations.AddField(
            model_name='country',
            name='descriptionFr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Fr'),
        ),
        migrations.AddField(
            model_name='country',
            name='descriptionHi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Hi'),
        ),
        migrations.AddField(
            model_name='country',
            name='descriptionTr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Tr'),
        ),
        migrations.AddField(
            model_name='country',
            name='descriptionVi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Vi'),
        ),
        migrations.AddField(
            model_name='country',
            name='explEs',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ülke Adı Es'),
        ),
        migrations.AddField(
            model_name='country',
            name='explFr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ülke Adı Fr'),
        ),
        migrations.AddField(
            model_name='country',
            name='explHi',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ülke Adı Hi'),
        ),
        migrations.AddField(
            model_name='country',
            name='explTr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ülke Adı Tr'),
        ),
        migrations.AddField(
            model_name='country',
            name='explVi',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ülke Adı Vi'),
        ),
        migrations.AddField(
            model_name='country',
            name='keywordsEs',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Es'),
        ),
        migrations.AddField(
            model_name='country',
            name='keywordsFr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Fr'),
        ),
        migrations.AddField(
            model_name='country',
            name='keywordsHi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Hi'),
        ),
        migrations.AddField(
            model_name='country',
            name='keywordsTr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Tr'),
        ),
        migrations.AddField(
            model_name='country',
            name='keywordsVi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Vi'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameEs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ülke Adı Es'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameFr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ülke Adı Fr'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameHi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ülke Adı Hi'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameTr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ülke Adı Tr'),
        ),
        migrations.AddField(
            model_name='country',
            name='nameVi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ülke Adı Vi'),
        ),
    ]
