# Generated by Django 4.0.3 on 2022-07-25 08:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_country_descriptiones_country_descriptionfr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptionEs',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Es'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptionFr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Fr'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptionHi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Hi'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptionTr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Tr'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptionVi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Vi'),
        ),
        migrations.AddField(
            model_name='category',
            name='explEs',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Keywords Es'),
        ),
        migrations.AddField(
            model_name='category',
            name='explFr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Keywords Fr'),
        ),
        migrations.AddField(
            model_name='category',
            name='explHi',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Keywords Hi'),
        ),
        migrations.AddField(
            model_name='category',
            name='explTr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Keywords Tr'),
        ),
        migrations.AddField(
            model_name='category',
            name='explVi',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Keywords Vi'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywordsEs',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Es'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywordsFr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Fr'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywordsHi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Hi'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywordsTr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Tr'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywordsVi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Vi'),
        ),
        migrations.AddField(
            model_name='category',
            name='nameEs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kategori Adı Es'),
        ),
        migrations.AddField(
            model_name='category',
            name='nameFr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kategori Adı Fr'),
        ),
        migrations.AddField(
            model_name='category',
            name='nameHi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kategori Adı Hi'),
        ),
        migrations.AddField(
            model_name='category',
            name='nameTr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kategori Adı Tr'),
        ),
        migrations.AddField(
            model_name='category',
            name='nameVi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kategori Adı Vi'),
        ),
        migrations.AddField(
            model_name='continent',
            name='nameEs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kıta Adı Es'),
        ),
        migrations.AddField(
            model_name='continent',
            name='nameFr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kıta Adı Fr'),
        ),
        migrations.AddField(
            model_name='continent',
            name='nameHi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kıta Adı Hi'),
        ),
        migrations.AddField(
            model_name='continent',
            name='nameTr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kıta Adı Tr'),
        ),
        migrations.AddField(
            model_name='continent',
            name='nameVi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kıta Adı Vi'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='nameEs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Es'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='nameFr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Fr'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='nameHi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Hi'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='nameTr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Tr'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='nameVi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Başlık Vi'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='explEs',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kısa Açıklama Es'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='explFr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kısa Açıklama Fr'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='explHi',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kısa Açıklama Hi'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='explTr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kısa Açıklama Tr'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='explVi',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kısa Açıklama Vi'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='short_explEs',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Es'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='short_explFr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Fr'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='short_explHi',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Hi'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='short_explTr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Tr'),
        ),
        migrations.AddField(
            model_name='quickinfo',
            name='short_explVi',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama Vi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='descriptionEs',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Es'),
        ),
        migrations.AddField(
            model_name='tag',
            name='descriptionFr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Fr'),
        ),
        migrations.AddField(
            model_name='tag',
            name='descriptionHi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Hi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='descriptionTr',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Tr'),
        ),
        migrations.AddField(
            model_name='tag',
            name='descriptionVi',
            field=models.TextField(blank=True, help_text='max 160 karakterli bir seo açıklaması', null=True, verbose_name='Google SEO Description Vi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywordsEs',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Es'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywordsFr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Fr'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywordsHi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Hi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywordsTr',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Tr'),
        ),
        migrations.AddField(
            model_name='tag',
            name='keywordsVi',
            field=models.TextField(blank=True, help_text='5 ila 10 tane anahtar kelimeyi aralarına virgül koyarak yazacaksın', null=True, verbose_name='Keywords Vi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nameEs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket Adı Es'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nameFr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket Adı Fr'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nameHi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket Adı Hi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nameTr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket Adı Tr'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nameVi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Etiket Adı Vi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='expl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='quickinfo',
            name='expl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kısa Açıklama'),
        ),
    ]
