# Generated by Django 4.0.3 on 2022-07-26 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_category_descriptionar_category_descriptionfa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='expl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='explAr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Ar'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explEs',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Es'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explFa',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Fa'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explFr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Fr'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explHi',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Hi'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explTr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Tr'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explUr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Ur'),
        ),
        migrations.AlterField(
            model_name='country',
            name='explVi',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ülke Adı Vi'),
        ),
    ]
