# Generated by Django 4.0.3 on 2022-08-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_country_expl_alter_country_explar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
    ]
