# Generated by Django 4.0.3 on 2022-08-02 19:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_content_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('create_date', models.DateField(default=app.models.return_date_time, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Footer Message',
                'verbose_name_plural': 'Footer Messages',
            },
        ),
        migrations.CreateModel(
            name='FooterSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('create_date', models.DateField(default=app.models.return_date_time, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Footer Subscribe',
                'verbose_name_plural': 'Footer Subscribes',
            },
        ),
    ]
