# Generated by Django 4.0.3 on 2022-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_footermessage_footersubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermessage',
            name='ip',
            field=models.CharField(max_length=200, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='footersubscribe',
            name='ip',
            field=models.CharField(max_length=200, null=True, verbose_name='IP'),
        ),
    ]
