# Generated by Django 4.0.3 on 2022-08-16 15:15

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0046_footermessage_ip_footersubscribe_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Name')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Surname')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=app.models.return_date_time, null=True, verbose_name='Profile Creation Date')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Model')),
            ],
        ),
    ]
