# Generated by Django 4.0.3 on 2022-08-17 10:19

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic Heading')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('date_created', models.DateTimeField(blank=True, default=app.models.return_date_time, null=True, verbose_name='Comment Date')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
