# Generated by Django 4.0.3 on 2022-08-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_comment_category_comment_country_entry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comments',
            field=models.ManyToManyField(related_name='comments_of_category', to='app.comment'),
        ),
        migrations.AddField(
            model_name='category',
            name='entries',
            field=models.ManyToManyField(related_name='entries_of_category', to='app.entry'),
        ),
        migrations.AddField(
            model_name='country',
            name='comments',
            field=models.ManyToManyField(related_name='comments_of_country', to='app.comment'),
        ),
        migrations.AddField(
            model_name='country',
            name='entries',
            field=models.ManyToManyField(related_name='entries_of_country', to='app.entry'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(related_name='comments_of_profile', to='app.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='entries',
            field=models.ManyToManyField(related_name='entries_of_profile', to='app.entry'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_comment', to='app.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_of_comment', to='app.country'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_comment', to='app.profile'),
        ),
    ]
