# Generated by Django 4.0.3 on 2022-08-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_category_comments_category_entries_country_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_of_comment', to='app.entry'),
        ),
    ]
