# Generated by Django 4.0.3 on 2022-08-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_comment_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date_created'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
