# Generated by Django 4.0.3 on 2022-08-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_created'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
