# Generated by Django 4.0.3 on 2022-08-21 14:50

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='/static/assets/images/defaultprofile.jpg', help_text='600x600', null=True, upload_to='blogs/', verbose_name="Profil Resmi'"),
        ),
    ]
