# Generated by Django 4.0.3 on 2022-08-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_comment_or_entry', to='app.profile'),
        ),
    ]
