# Generated by Django 4.0.3 on 2022-08-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_date_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
