# Generated by Django 4.0.3 on 2022-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments_of_profile', to='app.comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entries',
            field=models.ManyToManyField(blank=True, null=True, related_name='entries_of_profile', to='app.entry'),
        ),
    ]
