# Generated by Django 4.0.3 on 2022-08-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_profile_comments_alter_profile_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='category',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='country',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='country',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='entries',
        ),
    ]
