# Generated by Django 4.0.3 on 2022-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='secondComment',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Second Comment'),
        ),
    ]
