# Generated by Django 4.0.3 on 2022-08-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_foo_profile_encrypted_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Ülke', 'verbose_name_plural': 'Ülkeler'},
        ),
    ]
