# Generated by Django 4.0.3 on 2022-08-29 10:47

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpireCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=app.models.return_date_time, null=True, verbose_name='Code Creation Date')),
                ('encrypted_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foo_of_expirecode', to='app.foo')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_of_expirecode', to='app.profile')),
            ],
        ),
    ]
