# Generated by Django 4.0.3 on 2022-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_expirecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirecode',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Expired'),
        ),
    ]
