# Generated by Django 4.0.3 on 2022-08-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_expirecode_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expirecode',
            options={'ordering': ['-date_created']},
        ),
    ]
