# Generated by Django 4.0.3 on 2022-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_hottopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottopics',
            name='expired',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktif'),
        ),
    ]
