# Generated by Django 4.0.3 on 2022-09-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_hottopics_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hottopics',
            old_name='expired',
            new_name='status',
        ),
    ]
