# Generated by Django 4.0.3 on 2022-09-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_rename_expired_hottopics_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hottopics',
            name='heading',
        ),
        migrations.AddField(
            model_name='hottopics',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_of_hottopics', to='app.country'),
        ),
    ]
