# Generated by Django 4.0.3 on 2022-09-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_hottopics_explar_hottopics_exples_hottopics_explfa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-order'], 'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
    ]
