# Generated by Django 4.0.3 on 2022-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['order'], 'verbose_name': 'Kıta', 'verbose_name_plural': 'Kıtalar'},
        ),
        migrations.AddField(
            model_name='continent',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıralama'),
        ),
    ]
