# Generated by Django 4.0.3 on 2022-09-19 15:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_alter_continent_options_continent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic Heading')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('date_created', models.DateTimeField(blank=True, default=app.models.return_date_time, null=True, verbose_name='Comment Date')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Hot Topic',
                'verbose_name_plural': 'Hot Topics',
                'ordering': ['-date_created'],
            },
        ),
    ]
