# Generated by Django 4.0.3 on 2022-09-19 18:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_delete_hottopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='İsim')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Sözleşmeler',
                'verbose_name_plural': 'Sözleşme',
            },
        ),
    ]
