# Generated by Django 4.0.3 on 2022-09-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notified',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Subscribed?'),
        ),
    ]
