# Generated by Django 4.0.3 on 2022-09-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_profile_active_profile_notified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
    ]
