# Generated by Django 4.0.3 on 2022-10-17 12:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_alter_favorite_post_alter_favorite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('ip', models.CharField(max_length=200, null=True, verbose_name='IP')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='İsim')),
                ('create_date', models.DateField(default=app.models.return_date_time, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Contact Record',
                'verbose_name_plural': 'Contact Records',
            },
        ),
    ]
